apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stdout info;

    events {
      worker_connections 10;
    }

    http {
      access_log /dev/stdout;

      server {
        listen 80;

        error_page 404 /404.html;
        location /404.html {
          root /web;
        }

        location / {
          proxy_pass http://localhost:9292;
          proxy_intercept_errors on;
        }

      }
    }
  404.html: |
    <!DOCTYPE html>
    <html>
      <body>
        <h1>Oops!</h1>
        <h2>404 - The Page can't be found</h2>
        <a href="/">Back!</a>
      </body>
    </html>
