apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
        tier: frontend
    spec:
      containers:
        - name: app-frontend
          image: containersol/k8s-sample-app:1.0
          ports:
            - containerPort: 9292
