apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reference
  template:
    metadata:
      labels:
        app: reference
        tier: frontend
    spec:
      containers:
        - name: app-frontend
          image: dockleafdigital/k8s-simple-app:1.0
          ports:
            - containerPort: 8080
